//! One-shot generator for the committed DTLS certificate fixture.
//!
//! Run with `cargo run --bin gen_fixture > src/fixture.rs` to regenerate
//! `src/fixture.rs`. See `fuzz/README.md` for why the fixture is committed rather than
//! generated at startup.

use litep2p::transport::webrtc::DtlsCertificate;

fn main() {
    let certificate = DtlsCertificate::new().expect("certificate generation to succeed");
    let (cert, key) = certificate.as_parts();

    println!("//! Committed DTLS certificate fixture. Generated by `gen_fixture`.");
    println!("//!");
    println!(
        "//! certhash: {}",
        certificate.certhash_b64()
    );
    println!();
    emit("CERTIFICATE", cert);
    println!();
    emit("PRIVATE_KEY", key);
}

fn emit(name: &str, bytes: &[u8]) {
    println!("pub const {name}: &[u8] = &[");
    for chunk in bytes.chunks(16) {
        let line = chunk.iter().map(|byte| format!("0x{byte:02x},")).collect::<Vec<_>>().join(" ");
        println!("    {line}");
    }
    println!("];");
}
